### ISSUE TITLE
api not connecting with my app

### ISSUE THREAD

**Issue by Tslimshady99** [Casper-Oakley/RESTful-lenny#29]
i im getting this error from using lenny api
```
{ Error: connect ETIMEDOUT 95.85.2.152:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '95.85.2.152',
  port: 80,
  response: undefined }

**Comment by BadgerCode** [comment]
Hey. 

Sorry our host has gone down.
I'm looking into trying get this fixed asap.

I'll keep this updated.

**Comment by Tslimshady99** [comment]
Okay, thanks

**Comment by BadgerCode** [comment]
We have changed to a different host.
The domain name may take some time to update.
If you're able to flush/update your DNS cache, I would recommend doing that.

The domain name will point to the ip **redacted** (trying to access this Ip directly won't take you to the api).

Sorry for the inconvenience. We need to get analytics on this as we didn't actually know anyone was using it.

**Comment by BadgerCode** [comment]
If the domain isn't updating quick enough for you, there is a test domain available:
**redacted**

That domain will stop pointing to the API after a week.

**Comment by Tslimshady99** [comment]
Okay thanks very much.
